### ISSUE TITLE
Messages are out of order

### ISSUE THREAD

**Issue by byarmis** [barretobrock/cah_bot#11]
The prompt for the next card shows up before the winning card is displayed

**Comment by barretobrock** [comment]
With this change the process should be:
 - *Winner details*
 - _<wait 5 seconds>_
 - *New round's question
 - _<wait 5 seconds>_ 
 - *Players' prompts arrive*

I get that 5s might be a bit long, so I might trim that down in the future. For now, I'm just making sure it resolves the issue
